markdown: kramdown
highlighter: rouge
permalink: /:categories/:title.html 
excerpt_separator: "<!-- more -->"

github: 
author: "holly-juan"
email: winfirm#163.com
name: "holly Blog"
url: http://holly-juan.github.io
username: holly-juan
baseurl: /
domain: holly-juan.github.io

all_categories: [
  ["android", "Android开发","/android/index.html"], 
  ["react", "React Native", "/react/index.html"],
  ["web", "Web建站","/web/index.html"], 
  ["linux", "Linux相关","/linux/"],
  ["git", "git用法","/git/index.html"],
  ["program", "软件开发","/program/index.html"],
  ["vps", "VPS","/vps/index.html"],
  ["other", "杂记","/other/index.html"],
  ["read", "书摘","/read/index.html"], 
  ["about", "关于","/about.html"]
]

paginate: 6
paginate_path: "index_:num"

index_layout: "index.html"
category_layout: "_layouts/category.html"
tag_layout: "_layouts/tag.html"

#不使用gems库中的jekyll-paginate-category
#使用基于jekyll-paginate改写的的栏目分页插件，所以jekyll-paginate还需要用上。
# gems: [jekyll-paginate,jekyll-paginate-category]
gems: [jekyll-paginate]

collections:
  docs:
    output: true

copyright: []
#timezone: Asia/Shanghai
